sudo: required
services:
  - docker

before_install:
  - docker build -t wwkkww/complex-react-test -f ./client/Dockerfile.dev ./client
  - docker build -t wwkkww/complex-server-test -f ./server/Dockerfile.dev ./server

script:
  - docker run -e CI=true wwkkww/complex-react-test npm run test
  - docker run -e CI=true wwkkww/complex-server-test npm run test

after_success:
  - docker build -t wwkkww/multi-client ./client
  - docker build -t wwkkww/multi-nginx ./nginx
  - docker build -t wwkkww/multi-server ./server
  - docker build -t wwkkww/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push wwkkww/multi-client
  - docker push wwkkww/multi-nginx
  - docker push wwkkww/multi-server
  - docker push wwkkww/multi-worker

  deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: 'ap-southeast-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-ap-southeast-1-031203145391'
    bucket_path: 'docker-multi'
    on:
      branch: master